server:
  port: :8888
  timeout: 2s
db:
  host: localhost
  port: 5432
  username: dev
  password: dev
  dbname: lms
  sslmode: disable
jwt:
  secret: fj2oewihgfaso3ertigjsldkfpo3irweguhjq350orin
  token_ttl: 10h
